version: '3.8'

services:

  postgres:
    image: postgres:latest
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - services
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin', '-d', '${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    networks:
      - services
    environment:
      - API_PORT=${API_PORT}
      - API_URL=${API_URL}
      - PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}

  api:
    image: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    networks:
      - services
    environment:
      - WEB_URL=${WEB_URL}
      - API_URL=${API_URL}
      - PORT=${API_PORT}
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_PORT=${MONGODB_PORT}
    ports:
      - ${API_PORT}:${API_PORT}

networks:
  services: